In [49]:
import pandas as pd
import re

In [2]:
trip_advisor_csv = pd.read_csv('tripadvisor_hotel_reviews.csv')

In [3]:
trip_advisor_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  109 non-null    object
 1   Rating  109 non-null    int64
dtypes: int64(1), object(1)
memory usage: 1.8+ KB

In [4]:
trip_advisor_csv.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [5]:
trip_advisor_csv['Review'][0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews did valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe just noisy neighbors, aveda bath products nice, did not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience having pay 40 parking night,  '

In [8]:
trip_advisor_csv['Review_Lower'] = trip_advisor_csv['Review'].str.lower()

In [9]:
trip_advisor_csv.head()

,Review,Rating,Review_Lower
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso..."

# Remove Stopwords

In [105]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize

from nltk.stem import PorterStemmer

nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer

import pandas as pd

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/tejaswipinnaka/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/tejaswipinnaka/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/tejaswipinnaka/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [70]:
stopword = stopwords.words('english')
trip_advisor_csv['Review_without_stopwords'] \
= trip_advisor_csv['Review_Lower'] \
.apply(lambda x: ' '.join([word for word in x.split() if word not in stopword]))

In [64]:
trip_advisor_csv.head()

,Review,Rating,Review_Lower,Review_without_stopwords
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso..."

# Removing punctuation

In [91]:
trip_advisor_csv['Review_without_stopwords_no_punct'] \
= trip_advisor_csv['Review_without_stopwords'].apply(lambda x: re.sub(r"\*", "star", \
                                                                      x))

In [92]:
trip_advisor_csv.head()

,Review,Rating,Review_Lower,Review_without_stopwords,Review_without_stopwords_no_punct,tokenized,stemmed
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4star experience hotel monaco seatt...,"[nice, rooms, 4, experience, hotel, monaco, se...","[nice, room, 4, *, experi, hotel, monaco, seat..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","[unique, great, stay, wonderful, time, hotel, ...","[uniqu, ,, great, stay, ,, wonder, time, hotel..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, ,, went, seahawk, g..."

In [93]:
trip_advisor_csv['Review_without_stopwords_no_punct'] \
= trip_advisor_csv['Review_without_stopwords_no_punct'].apply(lambda x: re.sub(r"[^\w\s]", "", \
                                                                      x))

In [95]:
trip_advisor_csv.head()

,Review,Rating,Review_Lower,Review_without_stopwords,Review_without_stopwords_no_punct,tokenized,stemmed
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4star experience hotel monaco seatt...,"[nice, rooms, 4, experience, hotel, monaco, se...","[nice, room, 4, *, experi, hotel, monaco, seat..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ...","[uniqu, ,, great, stay, ,, wonder, time, hotel..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, ,, went, seahawk, g..."

# Tokenization

In [96]:
trip_advisor_csv['tokenized'] = trip_advisor_csv['Review_without_stopwords_no_punct'].apply\
(lambda x: word_tokenize(x))

In [97]:
trip_advisor_csv.head()

,Review,Rating,Review_Lower,Review_without_stopwords,Review_without_stopwords_no_punct,tokenized,stemmed
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4star experience hotel monaco seatt...,"[nice, rooms, 4star, experience, hotel, monaco...","[nice, room, 4, *, experi, hotel, monaco, seat..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ...","[uniqu, ,, great, stay, ,, wonder, time, hotel..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, ,, went, seahawk, g..."

# Stemming

In [98]:
ps = PorterStemmer()

trip_advisor_csv['stemmed'] = trip_advisor_csv['tokenized'].apply\
(lambda x: [ps.stem(token) for token in x])

In [100]:
trip_advisor_csv.head()

,Review,Rating,Review_Lower,Review_without_stopwords,Review_without_stopwords_no_punct,tokenized,stemmed
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4star experience hotel monaco seatt...,"[nice, rooms, 4star, experience, hotel, monaco...","[nice, room, 4star, experi, hotel, monaco, sea..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ...","[uniqu, great, stay, wonder, time, hotel, mona..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game..."

# Lemmatization

In [103]:
lm = WordNetLemmatizer()

trip_advisor_csv['lemmatized'] = trip_advisor_csv['stemmed'].apply\
(lambda x: [lm.lemmatize(token) for token in x])

In [104]:
trip_advisor_csv.head()

,Review,Rating,Review_Lower,Review_without_stopwords,Review_without_stopwords_no_punct,tokenized,stemmed,lemmatized
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s...","[nice, hotel, expens, park, got, good, deal, s..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi...","[ok, noth, special, charg, diamond, member, hi..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4star experience hotel monaco seatt...,"[nice, rooms, 4star, experience, hotel, monaco...","[nice, room, 4star, experi, hotel, monaco, sea...","[nice, room, 4star, experi, hotel, monaco, sea..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ...","[uniqu, great, stay, wonder, time, hotel, mona...","[uniqu, great, stay, wonder, time, hotel, mona..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game..."

# N-grams

In [108]:
tokens = sum(trip_advisor_csv['lemmatized'], [])

print(pd.Series(nltk.ngrams(tokens, 1)).value_counts())
print(pd.Series(nltk.ngrams(tokens, 2)).value_counts())
print(pd.Series(nltk.ngrams(tokens, 3)).value_counts())

(hotel,)       292
(room,)        275
(stay,)        160
(great,)       126
(staff,)        90
              ...
(idea,)          1
(250night,)      1
(affect,)        1
(175,)           1
(slipper,)       1
Name: count, Length: 2274, dtype: int64
(great, locat)       24
(space, needl)       21
(hotel, monaco)      16
(stay, hotel)        15
(staff, friendli)    13
                     ..
(start, minut)        1
(room, start)         1
(chang, 3)            1
(warwick, chang)      1
(food, raffl)         1
Name: count, Length: 8051, dtype: int64
(pike, place, market)        8
(view, space, needl)         5
(staff, friendli, help)      5
(hotel, great, locat)        5
(stay, crown, plaza)         5
                            ..
(central, seattl, handi)     1
(travel, central, seattl)    1
(free, travel, central)      1
(cheap, free, travel)        1
(hotel, right, street)       1
Name: count, Length: 9155, dtype: int64