# Basics

In [1]:
import pandas as pd

In [2]:
pd.DataFrame({'Yes': [51, 60], 'No': [30, 40]})

   Yes  No
0   51  30
1   60  40

In [9]:
df = pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

df.style.set_properties(**{'text-align': 'left'})

In [11]:
df = pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']}, index = ['Product A', 'Product B'])

df.style.set_properties(**{'text-align': 'left'})

In [14]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [18]:
pd.Series([1, 2, 3, 4, 5], index = ['a', 'b', 'c', 'd', 'e'], name = 'rolls')

a    1
b    2
c    3
d    4
e    5
Name: rolls, dtype: int64

In [27]:
fruits = pd.DataFrame({'Apples': [30], 'Bananas': [21]})
fruits

   Apples  Bananas
0      30       21

# CSV Files

In [23]:
wine_reviews = pd.read_csv('winemag-data-130k-v2.csv', index_col = 0)

# Indexing, Selecting and Assigning

In [20]:
wine_reviews.shape

(129971, 14)

In [24]:
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [28]:
wine_reviews.country

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [127]:
wine_reviews['country']

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [128]:
wine_reviews['pointtoprice'] = (wine_reviews.points)/(wine_reviews.price)
wine_reviews.head()
wine_reviews.pointtoprice.max()
wine_reviews.loc[wine_reviews.pointtoprice.idxmax(), 'title']

'Bandit NV Merlot (California)'

# Map and Apply

In [129]:
import pandas as pd
count_tropical = 0
count_fruity = 0
for series in wine_reviews['description']:
    if 'tropical' in series:
        count_tropical += 1
    if 'fruity' in series:
        count_fruity += 1
        

descriptor_counts = pd.Series([count_tropical, count_fruity])
descriptor_counts

0    3607
1    9090
dtype: int64

In [130]:
n_trop = wine_reviews.description.map(lambda desc: "tropical" in desc).sum()
n_fruity = wine_reviews.description.map(lambda desc: "fruity" in desc).sum()
descriptor_counts = pd.Series([n_trop, n_fruity], index=['tropical', 'fruity'])
descriptor_counts

tropical    3607
fruity      9090
dtype: int64

In [175]:
def stars(row):
    if row['points'] >= 95:
            return 3
    elif row['points'] >= 85 or row['points'] < 95:
            return 2
    elif row['points'] < 85:
            return 1
    elif row['country'] == 'Canada':
            return 3

wine_reviews['star_ratings'] = wine_reviews.apply(stars, axis = 'columns')
wine_reviews['star_ratings']

0         2
1         2
2         2
3         2
4         2
         ..
129966    2
129967    2
129968    2
129969    2
129970    2
Name: star_ratings, Length: 129971, dtype: int64

# Grouping and Sorting

In [176]:
wine_reviews.groupby('points').points.count()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [213]:
wine_reviews.points.value_counts().sort_index()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: count, dtype: int64

In [183]:
wine_reviews.groupby('country').points.min()

country
Argentina                 80
Armenia                   87
Australia                 80
Austria                   82
Bosnia and Herzegovina    85
Brazil                    80
Bulgaria                  80
Canada                    82
Chile                     80
China                     89
Croatia                   81
Cyprus                    85
Czech Republic            84
Egypt                     84
England                   89
France                    80
Georgia                   82
Germany                   81
Greece                    82
Hungary                   81
India                     87
Israel                    80
Italy                     80
Lebanon                   82
Luxembourg                88
Macedonia                 84
Mexico                    80
Moldova                   82
Morocco                   85
New Zealand               80
Peru                      80
Portugal                  80
Romania                   82
Serbia                    86
Slovakia                  87
Slovenia                  82
South Africa              82
Spain                     80
Switzerland               83
Turkey                    84
US                        80
Ukraine                   82
Uruguay                   80
Name: points, dtype: int64

In [185]:
wine_reviews.groupby('winery').apply(lambda d: d.title.iloc[0])

/var/folders/_c/9gq7j1g91c5b8106chgy6tbr0000gn/T/ipykernel_59658/2514182365.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  wine_reviews.groupby('winery').apply(lambda d: d.title.iloc[0])

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

In [192]:
wine_reviews.groupby('winery').title.first()

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Name: title, Length: 16757, dtype: object

In [197]:
wine_reviews.groupby(['winery', 'title']).points.max()

winery    title
1+1=3     1+1=3 2008 Rosé Cabernet Sauvignon (Penedès)                                     82
          1+1=3 NV Brut Sparkling (Cava)                                                   87
          1+1=3 NV Cygnus Brut Nature Reserva Made With Organic Grapes Sparkling (Cava)    89
          1+1=3 NV Rosé Sparkling (Cava)                                                   86
10 Knots  10 Knots 2006 Beachcomber White (Paso Robles)                                    83
                                                                                           ..
àMaurice  àMaurice 2014 Fred Estate Syrah (Walla Walla Valley (WA))                        88
          àMaurice NV Pour Me Red (Columbia Valley (WA))                                   89
Štoka     Štoka 2009 Izbrani Teran (Kras)                                                  88
          Štoka 2011 Grganja Vitovska (Kras)                                               90
          Štoka 2011 Izbrani Teran (Kras)                                                  90
Name: points, Length: 118840, dtype: int64

In [226]:
best_rating_per_price = wine_reviews.groupby('price').apply(lambda d: d.loc[d.points.idxmax()])
best_rating_per_price

/var/folders/_c/9gq7j1g91c5b8106chgy6tbr0000gn/T/ipykernel_59658/127186889.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  best_rating_per_price = wine_reviews.groupby('price').apply(lambda d: d.loc[d.points.idxmax()])

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,point-to-price,pointtoprice,tokens,star_ratings
price,,,,,,,,,,,,,,,,,
4.0,US,"There's a lot going on in this Merlot, which i...",NaN,86,4.0,California,California,California Other,NaN,NaN,Bandit NV Merlot (California),Merlot,Bandit,21.500000,21.500000,"[There, 's, a, lot, going, on, in, this, Merlo...",2
5.0,Chile,More than decent; this is good SB with no bell...,Reserva,87,5.0,Aconcagua Valley,NaN,NaN,Michael Schachner,@wineschach,In Situ 2008 Reserva Sauvignon Blanc (Aconcagu...,Sauvignon Blanc,In Situ,17.400000,17.400000,"[More, than, decent, ;, this, is, good, SB, wi...",2
6.0,US,"Off-dry fruit conjures up flavors of grapes, a...",NaN,88,6.0,Idaho,Idaho,NaN,Paul Gregutt,@paulgwine,Ste. Chapelle 2001 Johannisberg Riesling (Idaho),Johannisberg Riesling,Ste. Chapelle,14.666667,14.666667,"[Off-dry, fruit, conjures, up, flavors, of, gr...",2
7.0,Portugal,"Richly tannic, this concentrated wine has grea...",Toutalga,91,7.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Herdade dos Machados 2012 Toutalga Red (Alente...,Portuguese Red,Herdade dos Machados,13.000000,13.000000,"[Richly, tannic, ,, this, concentrated, wine, ...",2
8.0,US,"With full ripeness, density and concentration,...",Winemaker's Select,91,8.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Snoqualmie 2006 Winemaker's Select Riesling (C...,Riesling,Snoqualmie,11.375000,11.375000,"[With, full, ripeness, ,, density, and, concen...",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1900.0,France,"A massive wine for Margaux, packed with tannin...",NaN,98,1900.0,Bordeaux,Margaux,NaN,Roger Voss,@vossroger,Château Margaux 2009 Margaux,Bordeaux-style Red Blend,Château Margaux,0.051579,0.051579,"[A, massive, wine, for, Margaux, ,, packed, wi...",3
2000.0,France,This extravagantly perfumed wine has great jui...,NaN,97,2000.0,Bordeaux,Pomerol,NaN,Roger Voss,@vossroger,Château Pétrus 2011 Pomerol,Bordeaux-style Red Blend,Château Pétrus,0.048500,0.048500,"[This, extravagantly, perfumed, wine, has, gre...",3
2013.0,US,The nose on this single-vineyard wine from a s...,Roger Rose Vineyard,91,2013.0,California,Arroyo Seco,Central Coast,Matt Kettmann,@mattkettmann,Blair 2013 Roger Rose Vineyard Chardonnay (Arr...,Chardonnay,Blair,0.045206,0.045206,"[The, nose, on, this, single-vineyard, wine, f...",2
2500.0,France,The wine is a velvet glove in an iron fist. Th...,NaN,96,2500.0,Bordeaux,Pomerol,NaN,Roger Voss,@vossroger,Château Pétrus 2014 Pomerol,Bordeaux-style Red Blend,Château Pétrus,0.038400,0.038400,"[The, wine, is, a, velvet, glove, in, an, iron...",3
3300.0,France,This ripe wine shows plenty of blackberry frui...,NaN,88,3300.0,Bordeaux,Médoc,NaN,Roger Voss,@vossroger,Château les Ormes Sorbet 2013 Médoc,Bordeaux-style Red Blend,Château les Ormes Sorbet,0.026667,0.026667,"[This, ripe, wine, shows, plenty, of, blackber...",2

In [231]:
best_rating_per_price = wine_reviews.groupby('price').apply(lambda d: d.loc[d['points'].idxmax(), 'points'])
best_rating_per_price

/var/folders/_c/9gq7j1g91c5b8106chgy6tbr0000gn/T/ipykernel_59658/30957469.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  best_rating_per_price = wine_reviews.groupby('price').apply(lambda d: d.loc[d['points'].idxmax(), 'points'])

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Length: 390, dtype: int64

In [241]:
price_extremes = wine_reviews.groupby('variety').price.agg([min, max]).sort_values(by='min', ascending = False)
price_extremes

/var/folders/_c/9gq7j1g91c5b8106chgy6tbr0000gn/T/ipykernel_59658/1418778907.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  price_extremes = wine_reviews.groupby('variety').price.agg([min, max]).sort_values(by='min', ascending = False)
/var/folders/_c/9gq7j1g91c5b8106chgy6tbr0000gn/T/ipykernel_59658/1418778907.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  price_extremes = wine_reviews.groupby('variety').price.agg([min, max]).sort_values(by='min', ascending = False)

                                  min    max
variety
Ramisco                         495.0  495.0
Terrantez                       236.0  236.0
Francisa                        160.0  160.0
Rosenmuskateller                150.0  150.0
Tinta Negra Mole                112.0  112.0
...                               ...    ...
Roscetto                          NaN    NaN
Sauvignon Blanc-Sauvignon Gris    NaN    NaN
Tempranillo-Malbec                NaN    NaN
Vital                             NaN    NaN
Zelen                             NaN    NaN

[707 rows x 2 columns]

In [244]:
country_variety_counts = wine_reviews.groupby(['country', 'variety']).title.count()
country_variety_counts

country    variety
Argentina  Barbera                         1
           Bonarda                       105
           Bordeaux-style Red Blend       89
           Bordeaux-style White Blend      1
           Cabernet Blend                  8
                                        ...
Uruguay    Tannat-Cabernet Franc           2
           Tannat-Merlot                   6
           Tannat-Syrah                    1
           Tempranillo-Tannat              1
           White Blend                     1
Name: title, Length: 1612, dtype: int64